version: '3.5'
services:
    mysql8:
        image: silvaffabio/mysql8:v1
        restart: unless-stopped
        container_name: mysql8
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=teste
        volumes:
            - mysql8:/var/lib/mysql

volumes:
    mysql8:
